// Deterministic French grammar index (A1 → C2, level-major).
import type { GrammarIndexEntry } from "./ja";

export const FR_GRAMMAR_INDEX: (Omit<GrammarIndexEntry, "level"> & {
  level: "A1" | "A2" | "B1" | "B2" | "C1" | "C2"; // CEFR
})[] = [
  { slug: "pronunciation-spelling", title_tr: "Telaffuz ve Yazım (aksanlar, sessiz harfler, liaison)", category: "writing", level: "A1" },
  { slug: "gender-of-nouns", title_tr: "İsimlerde Cinsiyet (le/la ayrımı)", category: "nouns", level: "A1" },
  { slug: "definite-indefinite-articles", title_tr: "Tanımlıklar: le/la/les, un/une/des", category: "nouns", level: "A1" },
  { slug: "plural-forms", title_tr: "Çoğul Yapımı (-s, -x, -aux)", category: "nouns", level: "A1" },
  { slug: "subject-pronouns", title_tr: "Kişi Zamirleri (je, tu, il, on...)", category: "nouns", level: "A1" },
  { slug: "etre-avoir", title_tr: "être ve avoir Fiilleri", category: "verbs", level: "A1" },
  { slug: "er-verbs-present", title_tr: "-er Fiillerinin Şimdiki Zamanı", category: "verbs", level: "A1" },
  { slug: "ir-re-verbs-present", title_tr: "-ir ve -re Fiillerinin Şimdiki Zamanı", category: "verbs", level: "A1" },
  { slug: "negation-ne-pas", title_tr: "Olumsuzluk: ne ... pas", category: "syntax", level: "A1" },
  { slug: "question-formation", title_tr: "Soru Cümleleri (est-ce que, tonlama, devrik)", category: "syntax", level: "A1" },
  { slug: "numbers-time", title_tr: "Sayılar ve Saat", category: "numbers", level: "A1" },
  { slug: "adjective-agreement", title_tr: "Sıfat Uyumu ve Yeri", category: "adjectives", level: "A1" },
  { slug: "possessive-adjectives", title_tr: "İyelik Sıfatları (mon, ma, mes)", category: "nouns", level: "A1" },
  { slug: "aller-venir", title_tr: "aller ve venir; Yakın Gelecek (aller + mastar)", category: "verbs", level: "A1" },
  { slug: "partitive-articles", title_tr: "Parçacıl Tanımlık (du, de la, des)", category: "nouns", level: "A1" },
  { slug: "prepositions-basic", title_tr: "Temel Edatlar (à, de, en, chez) ve Bitişmeler (au, du)", category: "syntax", level: "A1" },
  { slug: "passe-compose-avoir", title_tr: "Geçmiş Zaman: Passé Composé (avoir ile)", category: "verbs", level: "A2" },
  { slug: "passe-compose-etre", title_tr: "être ile Passé Composé ve Ortaç Uyumu", category: "verbs", level: "A2" },
  { slug: "imparfait", title_tr: "Imparfait: Süreklilik ve Betimleme", category: "verbs", level: "A2" },
  { slug: "passe-compose-vs-imparfait", title_tr: "Passé Composé mü Imparfait mi?", category: "verbs", level: "A2" },
  { slug: "reflexive-verbs", title_tr: "Dönüşlü Fiiller (se lever, s'appeler)", category: "verbs", level: "A2" },
  { slug: "futur-simple", title_tr: "Gelecek Zaman: Futur Simple", category: "verbs", level: "A2" },
  { slug: "modal-verbs", title_tr: "pouvoir, devoir, vouloir, savoir", category: "verbs", level: "A2" },
  { slug: "object-pronouns", title_tr: "Nesne Zamirleri (le, la, lui, leur)", category: "nouns", level: "A2" },
  { slug: "y-en-pronouns", title_tr: "y ve en Zamirleri", category: "nouns", level: "A2" },
  { slug: "demonstratives", title_tr: "İşaret Sıfat ve Zamirleri (ce, cette, celui)", category: "nouns", level: "A2" },
  { slug: "comparatives", title_tr: "Karşılaştırma ve Üstünlük (plus... que, le plus)", category: "adjectives", level: "A2" },
  { slug: "adverb-formation", title_tr: "Belirteç Yapımı (-ment) ve Yeri", category: "adjectives", level: "A2" },
  { slug: "imperative-mood", title_tr: "Emir Kipi", category: "verbs", level: "A2" },
  { slug: "quantifiers", title_tr: "Miktar İfadeleri (beaucoup de, assez de, trop de)", category: "nouns", level: "A2" },
  { slug: "impersonal-expressions", title_tr: "Kişisiz Yapılar (il y a, il faut, hava durumu)", category: "syntax", level: "A2" },
  { slug: "relative-pronouns", title_tr: "İlgi Zamirleri (qui, que, dont, où)", category: "syntax", level: "B1" },
  { slug: "plus-que-parfait", title_tr: "Plus-que-parfait (geçmişin geçmişi)", category: "verbs", level: "B1" },
  { slug: "conditionnel-present", title_tr: "Conditionnel Présent: Kibarlık ve Varsayım", category: "verbs", level: "B1" },
  { slug: "si-clauses", title_tr: "Koşul Cümleleri (si + zaman uyumu)", category: "syntax", level: "B1" },
  { slug: "subjonctif-present", title_tr: "Subjonctif Présent'a Giriş (il faut que...)", category: "verbs", level: "B1" },
  { slug: "passive-voice", title_tr: "Edilgen Çatı (être + ortaç, par)", category: "verbs", level: "B1" },
  { slug: "gerondif", title_tr: "Gérondif (en + -ant)", category: "verbs", level: "B1" },
  { slug: "indirect-speech", title_tr: "Dolaylı Anlatım ve Zaman Uyumu", category: "syntax", level: "B1" },
  { slug: "double-pronouns", title_tr: "Çift Zamir Sıralaması (le lui, m'en)", category: "nouns", level: "B1" },
  { slug: "negation-advanced", title_tr: "İleri Olumsuzluk (ne... jamais/rien/personne/plus)", category: "syntax", level: "B1" },
  { slug: "verbs-with-prepositions", title_tr: "Edatlı Fiiller (penser à, parler de, réussir à)", category: "verbs", level: "B1" },
  { slug: "interrogative-pronouns", title_tr: "Soru Zamirleri (lequel, quoi, qu'est-ce qui)", category: "syntax", level: "B1" },
  { slug: "tout-usage", title_tr: "tout'nun Kullanımları (tout, toute, tous, toutes)", category: "adjectives", level: "B1" },
  { slug: "connectors-basic", title_tr: "Bağlaçlar (parce que, donc, pourtant, alors que)", category: "syntax", level: "B1" },
  { slug: "depuis-pendant-il-y-a", title_tr: "Zaman İfadeleri: depuis, pendant, il y a, dans", category: "syntax", level: "B1" },
  { slug: "subjonctif-usage", title_tr: "Subjonctif'in Kullanım Alanları (istek, duygu, şüphe)", category: "verbs", level: "B2" },
  { slug: "subjonctif-passe", title_tr: "Subjonctif Passé", category: "verbs", level: "B2" },
  { slug: "conditionnel-passe", title_tr: "Conditionnel Passé ve Geçmiş Koşul (si + plus-que-parfait)", category: "verbs", level: "B2" },
  { slug: "futur-anterieur", title_tr: "Futur Antérieur", category: "verbs", level: "B2" },
  { slug: "past-infinitive", title_tr: "Geçmiş Mastar (après avoir fait)", category: "verbs", level: "B2" },
  { slug: "participle-clauses", title_tr: "Ortaç Cümlecikleri (ayant terminé, une fois parti)", category: "verbs", level: "B2" },
  { slug: "causative-faire", title_tr: "faire ile Ettirgen Yapı (faire faire, se faire + mastar)", category: "verbs", level: "B2" },
  { slug: "agreement-advanced", title_tr: "İleri Ortaç Uyumu (öne alınmış COD, dönüşlü fiiller)", category: "verbs", level: "B2" },
  { slug: "relative-advanced", title_tr: "İleri İlgi Cümlecikleri (lequel + edat, ce qui / ce que)", category: "syntax", level: "B2" },
  { slug: "cleft-sentences", title_tr: "Vurgu Yapıları (c'est ... qui / que)", category: "syntax", level: "B2" },
  { slug: "nominalization", title_tr: "İsimleştirme (-tion, -age, -ment)", category: "nouns", level: "B2" },
  { slug: "discourse-connectors", title_tr: "Metin Bağlayıcıları (néanmoins, toutefois, ainsi, or)", category: "syntax", level: "B2" },
  { slug: "indefinite-pronouns", title_tr: "Belgisiz Zamirler (chacun, quiconque, n'importe qui)", category: "nouns", level: "B2" },
  { slug: "register-tu-vous", title_tr: "Dil Kayıtları: Günlük ve Resmî Fransızca (tu/vous)", category: "writing", level: "B2" },
  { slug: "passe-simple", title_tr: "Passé Simple (edebî geçmiş zaman)", category: "verbs", level: "C1" },
  { slug: "subjonctif-imparfait", title_tr: "Subjonctif Imparfait ve Edebî Kullanım", category: "verbs", level: "C1" },
  { slug: "ne-expletif", title_tr: "Açıklayıcı ne (ne explétif: avant qu'il ne parte)", category: "syntax", level: "C1" },
  { slug: "inversion-styles", title_tr: "Devrik Yapılar ve Biçemsel İnversiyon (peut-être est-il...)", category: "syntax", level: "C1" },
  { slug: "concession-opposition", title_tr: "Ödünleme ve Karşıtlık (bien que, quoique, avoir beau)", category: "syntax", level: "C1" },
  { slug: "mise-en-relief", title_tr: "Öne Çıkarma ve Konu-Yorum Yapısı (quant à, ce que... c'est)", category: "syntax", level: "C1" },
  { slug: "formal-prepositional-phrases", title_tr: "Resmî Edat Öbekleri (à l'égard de, en dépit de, au sein de)", category: "syntax", level: "C1" },
  { slug: "modalization", title_tr: "Kiplik ve Uzaklaşma (sembler, paraître, epistemik devoir)", category: "verbs", level: "C1" },
  { slug: "word-formation", title_tr: "Sözcük Türetme (ön ve son ekler: re-, dé-, -able, -eur)", category: "nouns", level: "C1" },
  { slug: "punctuation-style", title_tr: "Yazım ve Noktalama İncelikleri (tire, guillemets, boşluk kuralları)", category: "writing", level: "C1" },
  { slug: "ellipsis-gapping", title_tr: "Eksilti ve Ortak Öğe Düşürme", category: "syntax", level: "C1" },
  { slug: "text-cohesion", title_tr: "Metin Bağdaşıklığı ve Gönderim Zincirleri (celui-ci, ce dernier)", category: "syntax", level: "C1" },
  { slug: "passe-anterieur", title_tr: "Passé Antérieur ve Edebî Zaman Uyumu", category: "verbs", level: "C2" },
  { slug: "subjonctif-plus-que-parfait", title_tr: "Subjonctif Plus-que-parfait; İkinci Conditionnel Passé", category: "verbs", level: "C2" },
  { slug: "literary-registers", title_tr: "Edebî Biçem ve Anlatım Zamanları", category: "writing", level: "C2" },
  { slug: "nested-subclauses", title_tr: "İç İçe Yan Cümleler ve Uzun Bağımlılıklar", category: "syntax", level: "C2" },
  { slug: "stylistic-inversion", title_tr: "Biçemsel Devrikleme ve Ağır Öğe Kaydırma", category: "syntax", level: "C2" },
  { slug: "archaic-fixed-forms", title_tr: "Kalıplaşmış Eski Yapılar (fût-il, d'aucuns, n'eût été)", category: "nouns", level: "C2" },
  { slug: "francophone-varieties", title_tr: "Frankofoni Farkları (Québec, Belçika, İsviçre)", category: "writing", level: "C2" },
  { slug: "idiomatic-structures", title_tr: "Deyimsel Kalıplar ve Atasözü Yapıları", category: "syntax", level: "C2" },
];
