// Deterministic Dutch grammar index (A1 → C2, level-major).
import type { GrammarIndexEntry } from "./ja";

export const NL_GRAMMAR_INDEX: (Omit<GrammarIndexEntry, "level"> & {
  level: "A1" | "A2" | "B1" | "B2" | "C1" | "C2"; // CEFR
})[] = [
  { slug: "pronunciation-spelling", title_tr: "Telaffuz ve Yazım (ij, ui, g sesi)", category: "writing", level: "A1" },
  { slug: "de-het-articles", title_tr: "de / het Tanımlıkları", category: "nouns", level: "A1" },
  { slug: "plural-forms", title_tr: "Çoğul Yapımı (-en / -s)", category: "nouns", level: "A1" },
  { slug: "personal-pronouns", title_tr: "Kişi Zamirleri", category: "nouns", level: "A1" },
  { slug: "present-tense", title_tr: "Şimdiki/Geniş Zaman Çekimi", category: "verbs", level: "A1" },
  { slug: "zijn-hebben", title_tr: "zijn ve hebben Fiilleri", category: "verbs", level: "A1" },
  { slug: "word-order-v2", title_tr: "Kelime Dizilişi: V2 Kuralı", category: "syntax", level: "A1" },
  { slug: "negation-niet-geen", title_tr: "Olumsuzluk: niet / geen", category: "syntax", level: "A1" },
  { slug: "question-formation", title_tr: "Soru Cümleleri", category: "syntax", level: "A1" },
  { slug: "numbers-time", title_tr: "Sayılar ve Saat", category: "numbers", level: "A1" },
  { slug: "adjective-inflection", title_tr: "Sıfat Çekimi (-e takısı)", category: "adjectives", level: "A1" },
  { slug: "modal-verbs", title_tr: "Kip Fiilleri (kunnen, moeten, willen...)", category: "verbs", level: "A1" },
  { slug: "separable-verbs", title_tr: "Ayrılabilir Fiiller", category: "verbs", level: "A2" },
  { slug: "perfect-tense", title_tr: "Geçmiş Zaman: Perfectum", category: "verbs", level: "A2" },
  { slug: "imperfect-tense", title_tr: "Geçmiş Zaman: Imperfectum", category: "verbs", level: "A2" },
  { slug: "subordinate-clauses", title_tr: "Yan Cümleler ve Fiil Sona Atma", category: "syntax", level: "A2" },
  { slug: "er-usage", title_tr: "er Kullanımları", category: "syntax", level: "A2" },
  { slug: "comparatives", title_tr: "Karşılaştırma ve Üstünlük", category: "adjectives", level: "A2" },
  { slug: "future-tense", title_tr: "Gelecek Zaman (gaan / zullen)", category: "verbs", level: "A2" },
  { slug: "diminutives", title_tr: "Küçültme Ekleri (-je)", category: "nouns", level: "A2" },
  { slug: "reflexive-verbs", title_tr: "Dönüşlü Fiiller", category: "verbs", level: "B1" },
  { slug: "passive-voice", title_tr: "Edilgen Çatı (worden)", category: "verbs", level: "B1" },
  { slug: "conditional", title_tr: "Koşul Cümleleri (als, zou)", category: "syntax", level: "B1" },
  { slug: "relative-clauses", title_tr: "İlgi Cümlecikleri (die/dat/waar)", category: "syntax", level: "B1" },
  { slug: "aan-het-progressive", title_tr: "Sürerlik: aan het + Mastar, zitten/staan te", category: "verbs", level: "B1" },
  { slug: "om-te-infinitive", title_tr: "om ... te + Mastar Yapıları", category: "verbs", level: "B1" },
  { slug: "imperative-mood", title_tr: "Emir Kipi", category: "verbs", level: "B1" },
  { slug: "fixed-prepositions", title_tr: "Sabit Edatlı Fiiller (wachten op, denken aan)", category: "verbs", level: "B1" },
  { slug: "conjunctions", title_tr: "Bağlaçlar: Ana ve Yan Cümle Dizilişi (want/omdat)", category: "syntax", level: "B1" },
  { slug: "pronominal-adverbs", title_tr: "Zamirsel Belirteçler (eraan, erop, ermee)", category: "syntax", level: "B1" },
  { slug: "indirect-speech", title_tr: "Dolaylı Anlatım (dat/of cümleleri)", category: "syntax", level: "B1" },
  { slug: "possessives-genitive", title_tr: "İyelik Yapıları ve -s Tamlaması (van, Jans)", category: "nouns", level: "B1" },
  { slug: "adverb-formation", title_tr: "Belirteçler ve Derecelendirme (heel, erg, nogal)", category: "adjectives", level: "B1" },
  { slug: "pluperfect", title_tr: "Plusquamperfectum (had gedaan)", category: "verbs", level: "B2" },
  { slug: "conditional-perfect", title_tr: "Geçmiş Koşul (zou hebben gedaan)", category: "verbs", level: "B2" },
  { slug: "passive-tenses", title_tr: "Edilgenin Zamanları (wordt/werd/is gedaan)", category: "verbs", level: "B2" },
  { slug: "infinitive-clusters", title_tr: "Fiil Kümeleri (laten, zien, horen + mastar)", category: "verbs", level: "B2" },
  { slug: "laten-causative", title_tr: "laten ile Ettirgen Yapı", category: "verbs", level: "B2" },
  { slug: "inseparable-prefixes", title_tr: "Ayrılamaz Önekler (be-, ver-, ont-, her-)", category: "verbs", level: "B2" },
  { slug: "participle-adjectives", title_tr: "Ortaçların Sıfat Kullanımı (de gelezen krant)", category: "adjectives", level: "B2" },
  { slug: "word-order-inversion", title_tr: "Devrik Diziliş ve Vurgu (inversie)", category: "syntax", level: "B2" },
  { slug: "er-advanced", title_tr: "er'in İleri Kullanımları (kısmi er, edilgen özne)", category: "syntax", level: "B2" },
  { slug: "relative-advanced", title_tr: "İleri İlgi Cümlecikleri (wie, hetgeen, waar+edat)", category: "syntax", level: "B2" },
  { slug: "discourse-particles", title_tr: "Söylem Parçacıkları (toch, wel, maar, eens, even)", category: "syntax", level: "B2" },
  { slug: "comparative-clauses", title_tr: "Karşılaştırma Cümleleri (hoe...hoe, alsof, zoals)", category: "syntax", level: "B2" },
  { slug: "nominalization", title_tr: "Fiil İsimleştirme (het + mastar, -ing)", category: "nouns", level: "B2" },
  { slug: "men-formal-subjects", title_tr: "Genel Özne men ve Resmî u", category: "nouns", level: "B2" },
  { slug: "preposition-nuance", title_tr: "İnce Edat Ayrımları (op/aan/bij/tegen)", category: "syntax", level: "B2" },
  { slug: "negation-advanced", title_tr: "İleri Olumsuzluk (nauwelijks, geenszins, evenmin)", category: "syntax", level: "B2" },
  { slug: "triple-verb-clusters", title_tr: "Üçlü Fiil Kümeleri (zou hebben kunnen doen)", category: "verbs", level: "C1" },
  { slug: "impersonal-passive", title_tr: "Kişisiz Edilgen (er wordt gedanst)", category: "verbs", level: "C1" },
  { slug: "modality-nuance", title_tr: "Kiplik Nüansları (schijnen, blijken, lijken, horen te)", category: "verbs", level: "C1" },
  { slug: "subjunctive-remnants", title_tr: "Kalıplaşmış Dilek Kipi (leve, moge, het zij zo)", category: "verbs", level: "C1" },
  { slug: "te-infinitive-advanced", title_tr: "İleri te + Mastar Cümlelemeleri (alvorens te, zonder te)", category: "verbs", level: "C1" },
  { slug: "fronting-topicalization", title_tr: "Öne Alma ve Konu-Yorum Yapısı", category: "syntax", level: "C1" },
  { slug: "cleft-sentences", title_tr: "Yarık Cümleler (het is ... die/dat)", category: "syntax", level: "C1" },
  { slug: "correlative-conjunctions", title_tr: "İkili Bağlaçlar (zowel...als, noch...noch, hetzij)", category: "syntax", level: "C1" },
  { slug: "formal-prepositional-phrases", title_tr: "Resmî Edat Öbekleri (ten aanzien van, met betrekking tot)", category: "syntax", level: "C1" },
  { slug: "text-connectors", title_tr: "Metin Bağlayıcıları (bovendien, desondanks, daarentegen)", category: "syntax", level: "C1" },
  { slug: "word-formation", title_tr: "Sözcük Türetme (-heid, -baar, -lijk, -achtig)", category: "nouns", level: "C1" },
  { slug: "compound-nouns", title_tr: "Bileşik İsimler ve Bağlayıcı Sesler (-s-, -en-)", category: "nouns", level: "C1" },
  { slug: "punctuation-style", title_tr: "Yazım ve Noktalama İncelikleri (tussen-n, apostrof)", category: "writing", level: "C1" },
  { slug: "archaic-case-remnants", title_tr: "Kalıp Tamlamalar ve Eski Çekim İzleri (der, des, te allen tijde)", category: "nouns", level: "C2" },
  { slug: "literary-tenses", title_tr: "Edebî Anlatım Zamanları ve Tarihsel Şimdiki Zaman", category: "verbs", level: "C2" },
  { slug: "complex-passive-transforms", title_tr: "Karmaşık Edilgen Dönüşümleri (krijgen-edilgeni)", category: "verbs", level: "C2" },
  { slug: "ellipsis-gapping", title_tr: "Eksilti ve Ortak Öğe Düşürme", category: "syntax", level: "C2" },
  { slug: "nested-subclauses", title_tr: "İç İçe Yan Cümleler ve Uzun Bağımlılıklar", category: "syntax", level: "C2" },
  { slug: "stylistic-inversion", title_tr: "Biçemsel Devrikleme ve Ağır Öğe Kaydırma", category: "syntax", level: "C2" },
  { slug: "dummy-subjects-advanced", title_tr: "het/er Gölge Özneleri: İleri Durumlar", category: "syntax", level: "C2" },
  { slug: "nominal-style", title_tr: "İsimleştirilmiş Resmî Biçem (ambtelijk taalgebruik)", category: "writing", level: "C2" },
  { slug: "flemish-differences", title_tr: "Belçika Flamancası Farkları (gij, ge, sözcük seçimi)", category: "writing", level: "C2" },
  { slug: "idiomatic-structures", title_tr: "Deyimsel Kalıplar ve Atasözü Yapıları", category: "syntax", level: "C2" },
];
