#!/usr/bin/env node
// data/app.db'nin şemasını src/db/ddl.ts'e döker. Tarayıcı (sql.js) tarafında
// hiç kayıt yokken boş DB'yi bu DDL kurar. schema.ts değiştiğinde yeniden
// çalıştır: node scripts/gen-ddl.mjs
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const raw = execSync('sqlite3 data/app.db ".schema"', { encoding: "utf8" });
const stmts = raw
  .split(";\n")
  .map((s) => s.trim())
  .filter((s) => s && !s.startsWith("CREATE TABLE sqlite_"));

const out = `// AUTO-GENERATED by scripts/gen-ddl.mjs — do not edit by hand.
// Regenerate after any schema.ts shape change: node scripts/gen-ddl.mjs
export const DDL: string[] = ${JSON.stringify(stmts, null, 2)};
`;
writeFileSync("src/db/ddl.ts", out);
console.log(`src/db/ddl.ts: ${stmts.length} statement`);
